[package]
name = "flomo"
version = "0.1.0"
edition = "2021"
authors = ["Cheng Huang <cheng@duck.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
